sudo: required

language: bash
env:
  DOCKER_COMPOSE_VERSION: 1.9.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

services:
  - docker

script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY
  - docker build -t registry.le-corre.eu:5000/go:base -f docker/go_base.Dockerfile .
  - docker build -t go_test -f docker/go_test.Dockerfile .
  - docker run --rm -e WATCHING=1 go_test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY;
    docker build -t go_base -f docker/go_base.Dockerfile .;
    docker tag go_base $DOCKER_REGISTRY/go:base;
    docker push $DOCKER_REGISTRY/go:base;
    curl -X POST --header "Content-Type: application/json" --header "X-AUTH-TOKEN: ${DEPLOY_TOKEN}" -d '{
        "Image": "httpd:alpine",
        "ExposedPorts": {
            "80/tcp" : {}
        },
      "HostConfig":{
        "PortBindings": {
                  "80/tcp": [
                      {
                          "HostIp": "0.0.0.0",
                          "HostPort": "8080"
                      }
                  ]
              }
      },
      "Hostname": "test-master"
      }' http://${DEPLOY_URL}/deploy
    fi
  - if [ "$TRAVIS_BRANCH" == "developpement" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY;
    docker build -t go_base -f docker/go_base.Dockerfile .;
    docker tag go_base $DOCKER_REGISTRY/go:base-dev;
    docker push $DOCKER_REGISTRY/go:base-dev;
    curl -X POST --header "Content-Type: application/json" --header "X-AUTH-TOKEN: ${DEPLOY_TOKEN}" -d '{
        "Image": "httpd:alpine",
        "ExposedPorts": {
            "80/tcp" : {}
        },
      "HostConfig":{
        "PortBindings": {
                  "80/tcp": [
                      {
                          "HostIp": "0.0.0.0",
                          "HostPort": "8081"
                      }
                  ]
              }
      },
      "Hostname": "test-dev"
      }' http://${DEPLOY_URL}/deploy
    fi

notifications:
  slack: societyco:T1mHeYKrOtopvRjIZ68MqOQo
