sudo: required

language: bash

services:
  - docker

script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY
  - docker build -t registry.le-corre.eu:5000/go:base -f docker/go_base.Dockerfile .
  - docker build -t go_test -f docker/go_test.Dockerfile .
  - docker run --rm -e WATCHING=1 go_test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY;
    docker build -t go_base -f docker/go_base.Dockerfile .;
    docker tag go_base $DOCKER_REGISTRY/go:base;
    docker push $DOCKER_REGISTRY/go:base;
    fi
  - if [ "$TRAVIS_BRANCH" == "developpement" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY;
    docker build -t go_base -f docker/go_base.Dockerfile .;
    docker tag go_base $DOCKER_REGISTRY/go:base-dev;
    docker push $DOCKER_REGISTRY/go:base-dev;
    fi

notifications:
  slack: societyco:T1mHeYKrOtopvRjIZ68MqOQo
