sudo: required

language: bash
env:
  DOCKER_COMPOSE_VERSION: 1.9.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cp .env.test .env


services:
  - docker

script:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY
  - docker-compose build
  - ./popcube.sh -t -y all
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run back-test

after_success:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run back-test
  - >-
    if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY;
    docker build -t go_base -f docker/go_base.Dockerfile .;
    docker tag go_base $DOCKER_REGISTRY/go:base;
    docker push $DOCKER_REGISTRY/go:base;
    docker build -t nginx_front -f docker/nginx_front.Dockerfile .;
    docker tag nginx_front $DOCKER_REGISTRY/nginx_front:latest;
    docker push $DOCKER_REGISTRY/nginx_front:latest;
    curl -X POST --header 'Content-Type: application/json' --header "X-AUTH-TOKEN: ${DEPLOY_TOKEN}" -d '{ "Image": "registry.le-corre.eu:5000/nginx_front:latest", "Env": [ "VIRTUAL_NETWORK=nginx-proxy", "LETSENCRYPT_HOST=master.popcube.xyz", "LETSENCRYPT_EMAIL=clement@popcube.xyz", "VIRTUAL_HOST=master.popcube.xyz", "VIRTUAL_PORT=80" ], "Hostname": "nginx_front" }' http://${DEPLOY_URL}/deploy;
    fi
  - >-
    if [ "$TRAVIS_BRANCH" == "development" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PWD" $DOCKER_REGISTRY;
    docker build -t go_base -f docker/go_base.Dockerfile .;
    docker tag go_base $DOCKER_REGISTRY/go:base-dev;
    docker push $DOCKER_REGISTRY/go:base-dev;
    docker build -t nginx_front -f docker/nginx_front.Dockerfile .;
    docker tag nginx_front $DOCKER_REGISTRY/nginx_front:dev;
    docker push $DOCKER_REGISTRY/nginx_front:dev;
    curl -X POST --header 'Content-Type: application/json' --header "X-AUTH-TOKEN: ${DEPLOY_TOKEN}" -d '{ "Image": "registry.le-corre.eu:5000/nginx_front:dev", "Env": [ "VIRTUAL_NETWORK=nginx-proxy", "LETSENCRYPT_HOST=dev.popcube.xyz", "LETSENCRYPT_EMAIL=clement@popcube.xyz", "VIRTUAL_HOST=dev.popcube.xyz", "VIRTUAL_PORT=80" ], "Hostname": "nginx_front-dev" }' http://${DEPLOY_URL}/deploy;
    fi

notifications:
  slack: societyco:T1mHeYKrOtopvRjIZ68MqOQo
