sudo: required
dist: trusty
language: node_js - "7.7.2"
cache:
  directories:
  - app/node_modules
script:
- npm install electron electron-packager -g
- cd app; npm install; cd ..;
- electron-packager app Popcube --platform=darwin --arch=x64 --icon=logo/app.ico --overwrite
- electron-packager app Popcube --platform=linux --arch=x64 --icon=logo/app.ico --overwrite
- zip -r Popcube-linux-x64.zip Popcube-linux-x64
- zip -r Popcube-darwin-x64.zip Popcube-darwin-x64
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then fi
- if [ "$TRAVIS_BRANCH" == "development" ]; then fi
deploy:
  provider: releases
  api_key:
    secure: lKLjNdNl9TtZWgOWXnNzgPIen+2RzgqGp3mQyg+ZzBFXnW+NNhmYAa49LxdAkm1IaksmiDvO/oiqz+AloIOPq3iggJ/0XMJgkvHfPVFp8lxNJj+VyfZRCGcWazJCYR+fmpwranCd2yPNF+mPfMBbIhn6h+ZMQMi+8bQMiEQvpp66yLck544d+fBCzqIpJNvN41TGJ4Smlh5kOdXEQen1ZKytXM1Hzk9Jj6TT9Q8aTI1erJRFPH7+qPMsnL7+kknqaMx2pOditgmnMXZh94hfOuyD/jVhnrlvx4mk38VPSeuy2SaDdvKyz9wpcSOb2DZ79WljkFxGpkX66ufyp5QXcELMbNQz4/hXoBBl4hAK85p6JKOKYbNr1bNiUNGxQ/avh0wkS0lgSPuBd0B9fSYkUdo+l8tnIGUCRpAI1wyZdbu1pKYrL8WLs72M5ABjNHQV0iNJkK8ebZVxgLLr05ow7DH+dPgz18zGPYkyCM1syF4BDXdUGqeL4N8Pz2od3wATfrMi90VifvcMdktrZFRVYDRdCw1khYpgdYJEnc85IGYPR3knx/ZbxCs1fHTTtk5TtcJBa3RaztbsDUBbbqkOafd+vXUikLFBLsz9u7aXRObMdNe6KUyz4c/dE60elxBdOxue3vOYlDhFOkPwdgD4bLWouBrE0IKH0tcPcXyBXeA=
  file:
    - "Popcube-darwin-x64.zip"
    - "Popcube-linux-x64.zip"
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack: societyco:T1mHeYKrOtopvRjIZ68MqOQo
