sudo: required

language: bash

services:
  - docker

script:
  # - docker run -d ubuntu
  - docker build -t go_test -f docker/go_test.Dockerfile . && docker run --rm go_test

notifications:
  slack: societyco:T1mHeYKrOtopvRjIZ68MqOQo
