version: "2"
services:
  front:
    build:
      context: .
      dockerfile: docker/nginx_front.Dockerfile
    ports:
      - 8080:80
      - 443:443
    volumes:
      - "./app/:/usr/share/nginx/html/app"
      - "./docs/:/usr/share/nginx/html/docs"
  database:
    image: mongo:3.4.0
    hostname: mongo
  back-test:
    build:
      context: .
      dockerfile: docker/go_test.Dockerfile
    volumes:
      - "./go/src:/go/src"
      - "./docs:/home/docs"
      - "./coverage:/home/coverage"
