version: "2"
services:
  back:
    build:
      context: .
      dockerfile:  docker/go_base.Dockerfile
    image: registry.le-corre.eu:5000/go:base
  database:
    image: mariadb:10.1.20
    hostname: database
  front:
    build:
      context: .
      dockerfile: docker/nginx_front.Dockerfile